use crate::pipeline::SheetResult;

/// Generate CSS sprite definitions for a sprite sheet.
///
/// Produces a base class with the background-image, per-sprite classes
/// with width/height/background-position, and @media queries for retina.
pub fn serialize(
    sheet: &SheetResult,
    png_name: &str,
    base_name: &str,
    scale: u32,
    all_scale_names: &[(u32, String)],
) -> String {
    let mut css = String::new();

    css.push_str("/* Generated by pixelpipe -- do not edit */\n\n");

    // Base class
    css.push_str(&format!(
        ".{} {{\n  background-image: url('{}');\n  background-repeat: no-repeat;\n}}\n\n",
        base_name, png_name
    ));

    // Per-sprite classes
    // When scaled, coordinates in the sheet are already multiplied,
    // but CSS background-position should reference the 1x logical size.
    // The background-size property handles the rest.
    for frame in &sheet.frames {
        let logical_x = frame.x / scale;
        let logical_y = frame.y / scale;
        let logical_w = frame.width / scale;
        let logical_h = frame.height / scale;

        css.push_str(&format!(
            ".{}-{} {{\n  width: {}px;\n  height: {}px;\n  background-position: -{}px -{}px;\n}}\n",
            base_name,
            sanitize_css_name(&frame.name),
            logical_w,
            logical_h,
            logical_x,
            logical_y,
        ));
    }

    // Retina @media queries for higher scale variants
    for (variant_scale, variant_png) in all_scale_names {
        if *variant_scale <= 1 {
            continue;
        }
        let dpr = *variant_scale;
        let bg_w = sheet.width / scale; // logical width
        let bg_h = sheet.height / scale;

        css.push_str(&format!(
            "\n@media (-webkit-min-device-pixel-ratio: {}), (min-resolution: {}dpi) {{\n",
            dpr,
            dpr * 96
        ));
        css.push_str(&format!(
            "  .{} {{\n    background-image: url('{}');\n    background-size: {}px {}px;\n  }}\n",
            base_name, variant_png, bg_w, bg_h
        ));
        css.push_str("}\n");
    }

    css
}

fn sanitize_css_name(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_alphanumeric() || c == '-' { c } else { '-' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pipeline::{FramePlacement, SheetResult};
    use image::RgbaImage;

    #[test]
    fn test_css_output_basic() {
        let sheet = SheetResult {
            image: RgbaImage::new(64, 64),
            frames: vec![
                FramePlacement {
                    name: "sword".to_string(),
                    x: 0,
                    y: 0,
                    width: 16,
                    height: 16,
                },
                FramePlacement {
                    name: "shield".to_string(),
                    x: 17,
                    y: 0,
                    width: 16,
                    height: 16,
                },
            ],
            width: 64,
            height: 64,
        };

        let css = serialize(&sheet, "sprites.png", "sprites", 1, &[]);

        assert!(css.contains(".sprites {"));
        assert!(css.contains("background-image: url('sprites.png')"));
        assert!(css.contains(".sprites-sword {"));
        assert!(css.contains("width: 16px"));
        assert!(css.contains("background-position: -0px -0px"));
        assert!(css.contains(".sprites-shield {"));
        assert!(css.contains("background-position: -17px -0px"));
    }

    #[test]
    fn test_css_retina_media_query() {
        let sheet = SheetResult {
            image: RgbaImage::new(64, 64),
            frames: vec![FramePlacement {
                name: "icon".to_string(),
                x: 0,
                y: 0,
                width: 16,
                height: 16,
            }],
            width: 64,
            height: 64,
        };

        let scale_names = vec![
            (1, "sprites@1x.png".to_string()),
            (2, "sprites@2x.png".to_string()),
        ];

        let css = serialize(&sheet, "sprites@1x.png", "sprites", 1, &scale_names);

        assert!(css.contains("@media"));
        assert!(css.contains("-webkit-min-device-pixel-ratio: 2"));
        assert!(css.contains("min-resolution: 192dpi"));
        assert!(css.contains("url('sprites@2x.png')"));
        assert!(css.contains("background-size: 64px 64px"));
    }

    #[test]
    fn test_sanitize_css_name() {
        assert_eq!(sanitize_css_name("my_sprite"), "my-sprite");
        assert_eq!(sanitize_css_name("icon.large"), "icon-large");
        assert_eq!(sanitize_css_name("hero-idle"), "hero-idle");
    }
}
